### ISSUE TITLE
Unabale to use "Custom icons" for Authenticator: On loading aegis icon pack reports 'Unhandled Exception: PathNotFoundException: Creation of temporary directory failed, path = '/tmp/user/1000' '

### ISSUE THREAD

**Issue by bentolor** [flathub/com.yubico.yubioath#84]
I'm trying to load a Custom icons pack. This failes, regardless of the pack.

```
~  flatpak run com.yubico.yubioath
…
ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PathNotFoundException: Creation of temporary directory failed, path = '/tmp/user/1000' (OS Error: Datei oder Verzeichnis nicht gefunden, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _Directory.createTemp.<anonymous closure> (dart:io/directory_impl.dart:152)
<asynchronous suspension>
#2      IconPackManager.importPack (package:yubico_authenticator/oath/icon_provider/icon_pack_manager.dart:112)
<asynchronous suspension>
#3      _ImportActionChip._importAction (package:yubico_authenticator/oath/icon_provider/icon_pack_dialog.dart:184)
<asynchronous suspension>

```

**Comment by bentolor** [comment]
Nota bene: Using the application "Flatseal" and allowing access to the aforementioned directory fixes the error.

**Comment by Erick555** [comment]
App has no access to this path so manual override by user is right workaround for this.

You can put those icons in` ~/.var/app/com.yubico.yubioath/data` so app could access them in normal way.
