### ISSUE TITLE
Failed to open smart card connection

### ISSUE THREAD

**Issue by MrRinkana** [flathub/com.yubico.yubioath#90]
I'm not sure what changed but after updating my tumbleweed system today, I can no longer access my TOTP from yubikey authenticator:

Error is: "Failed to open smart card connection - _Make sure pcscd is installed and running_."

systemctl status pcscd returns: "active (running)"
 Installed packages are:
```
 S  | Name               | Summary                                                                    | Type
---+--------------------+----------------------------------------------------------------------------+--------
i  | libpcsclite1       | PC/SC Smart Card Library                                                   | package
i  | libpcsclite1-32bit | PC/SC Smart Card Library                                                   | package
i  | pcsc-ccid          | PCSC Driver for CCID Based Smart Card Readers and GemPC Twin Serial Reader | package
i  | pcsc-lite          | PC/SC Smart Cards Library                                                  | package

```

App is running as flatpak, system is opensuse tumbleweed version 20240810

I can check my passkeys trough the app, the home tab seems normal, I can see if the slots are configured.
TOTP and certificates do not work (same error)

**Comment by Erick555** [comment]
It's possible that opensuse tumbleweed updates pcsclite to 2.3.0 and you hit https://github.com/LudovicRousseau/PCSC/issues/199

You may check with `pcscd --version`

**Comment by MrRinkana** [comment]
This seems indeed to be the case, my pcsc version is 2.3.0.

I assume the flatpack app needs to update its bindings then?

Downgrading one package is not really a thing in tumbleweed as its a rolling release, and as the linked issue mentions wouldn't there be a risk other things break in the system instead?

**Comment by Erick555** [comment]
The problem with updating flatpak is that it will break non-rolling suse flavors alongside debian, ubuntu and everyone who didn't update to 2.3.0 yet. This is ugly choice for flatpak maintainer.

If you know how to downgrade one package on your system and feel comfortably with it then it's easiest workaround for now and buys some time.

**Comment by MrRinkana** [comment]
So there is no way for a flatpak to specify minimum version of a package? Such that an update would be blocked until the distro provides 2.3.0?

I understand that it might be a problem for frequently updated flatpaks, but this one (yubi aunth) is rather stable, maybe it would be possible?

**Comment by Erick555** [comment]
No, it's not possible for flatpak.

**Comment by MrRinkana** [comment]
That's a bummer.. Alright then i assume this issue should be closed as "can't fix", feel free to reopen if it's preferred to keep it as waiting on upstream!

**Comment by Erick555** [comment]
I think it's better to gave it opened for visibility for other users.

**Comment by hafeoz** [comment]
So I've created a PR #91 that bumps the pcsc-lite version so that the `flathubbot` can create a test build for it. My understanding is that anyone encountering the protocol version mismatch problem can use the test build instead.

**Comment by Fei1Yang** [comment]
@Erick555  Can you please merge this PR to the `beta` branch alongside with all the commits it currently lacking from the `master` branch, so users with pcsc 2.3 can install it from the `flathub-beta` repo instead of a flatpakref, therefore retaining auto update functionality?

**Comment by Erick555** [comment]
@Fei1Yang I'm not maintainer of this app - @Lunarequest is.

**Comment by MrRinkana** [comment]
Beta build with the version bump seems like the smoothest transition, i like that idea! Reopening both for visibility and since there is a feasible solution on the horizon in this repo

**Comment by Fei1Yang** [comment]
> Beta build with the version bump seems like the smoothest transition, i like that idea! Reopening both for visibility and since there is a feasible solution on the horizon in this repo

There is no such thing as "version bump" in flatpak ecosystem, however it also won't be very smooth, `flathub-beta` is another repository the user needed to add.

**Comment by suntorytimed** [comment]
Having the change in flathub-beta would be great. Right now it's sitting on 6.0.0 anyways. Unfortunately the flatpakref doesn't seem to be avaiable anymore.

**Comment by Erick555** [comment]
flathub doesn't allow force-push to release branches

**Comment by Erick555** [comment]
beta now supports pcsclite 2.3.0 and above. stable supports below 2.3.0

**Comment by edgan** [comment]
Others might be interested in actual instructions of how to build or install the beta.

#101

**Comment by bentolor** [comment]
After upgrading from Ubuntu 24.04 noble to Ubuntu 24.10 oracular, I face the same issue. 
Writing just for documentation:

### The error
     Failed to open smart card connection. Make sure pcscd is installed and running.

### The fix/workaround
As mentioned above: Install the beta version.

```
flatpak uninstall com.yubico.yubioath
flatpak remote-add --user --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
flatpak install flathub-beta com.yubico.yubioath
```

**Comment by Aqua1ung** [comment]
Is this supposed to have been fixed in ver. 7.3.0? I am currently running 7.3.0 Flaptak, yet I am still running into the same issue. And yes, pcscd is up and running:
```
[dad@DadsGram ~]$ systemctl status pcscd
● pcscd.service - PC/SC Smart Card Daemon
     Loaded: loaded (/usr/lib/systemd/system/pcscd.service; indirect; preset: disabled)
     Active: active (running) since Fri 2025-10-17 16:34:54 EDT; 13min ago
 Invocation: 4fb1c54be9c741bc8773647d725eaaa1
TriggeredBy: ● pcscd.socket
       Docs: man:pcscd(8)
   Main PID: 68949 (pcscd)
      Tasks: 5 (limit: 37988)
     Memory: 3.8M (peak: 5.1M)
        CPU: 5.941s
     CGroup: /system.slice/pcscd.service
             └─68949 /usr/bin/pcscd --foreground --auto-exit

Oct 17 16:34:54 DadsGram systemd[1]: Started PC/SC Smart Card Daemon.```

**Comment by Erick555** [comment]
Which distro? Please show `flatpak info com.yubico.yubioath` output.

The initial 7.3.0 update had it broken but the subsequent one should fix it. Ensure you have `9e2b36710a4b39367a0b55a66ffa1cb9545041c46a2f863e0e941200c7e56814` commit installed otherwise run `flatpak update`.  If it didn't work before 7.3.0 update then it could be different problem.

**Comment by Aqua1ung** [comment]
> Which distro?

Archlinux.

> Please show `flatpak info com.yubico.yubioath` output.
```
[dad@DadsGram ~]$ flatpak info com.yubico.yubioath

Yubico Authenticator - Graphical interface for displaying OATH codes with a
YubiKey

          ID: com.yubico.yubioath
         Ref: app/com.yubico.yubioath/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 7.3.0
     License: BSD-2-Clause
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 111.2 MB
     Runtime: org.freedesktop.Platform/x86_64/25.08
         Sdk: org.freedesktop.Sdk/x86_64/25.08

      Commit: 9e2b36710a4b39367a0b55a66ffa1cb9545041c46a2f863e0e941200c7e56814
      Parent: e10ba537eee382d60b578290e698a1e6f5566d5f436ba4663d2ef7b3f8caf6d2
     Subject: Merge pull request #129 from Erick555/Erick555-patch-1 (49cf9b722d33)
        Date: 2025-10-16 18:40:58 +0000
[dad@DadsGram ~]$ systemctl status pcscd
● pcscd.service - PC/SC Smart Card Daemon
     Loaded: loaded (/usr/lib/systemd/system/pcscd.service; indirect; preset: disabled)
     Active: active (running) since Sat 2025-10-18 12:04:53 EDT; 13s ago
 Invocation: 8adce73668e144a6bce1cd948640f038
TriggeredBy: ● pcscd.socket
       Docs: man:pcscd(8)
   Main PID: 21174 (pcscd)
      Tasks: 5 (limit: 38054)
     Memory: 2.9M (peak: 3.4M)
        CPU: 213ms
     CGroup: /system.slice/pcscd.service
             └─21174 /usr/bin/pcscd --foreground --auto-exit

Oct 18 12:04:53 DadsGram systemd[1]: Started PC/SC Smart Card Daemon.
[dad@DadsGram ~]$ flatpak update
Looking for updates…

Nothing to do.
```

<img width="1098" height="752" alt="Image" src="https://github.com/user-attachments/assets/638214a8-91e0-432d-b84f-c5fa04ea8779" />

**Comment by Erick555** [comment]
Then it must be some different issue than this one. I tested Archlinux myself and it works there.

You may try [beta](https://github.com/flathub/com.yubico.yubioath/issues/90#issuecomment-2483064653) but for Arch it shouldn't make any difference.

**Comment by Erick555** [comment]
Do you have latest pcscd 2.3.3? `pcscd --version`
Did you tweaked any flatpak permissions? `flatpak info -M com.yubico.yubioath`

**Comment by Aqua1ung** [comment]
> Do you have latest pcscd 2.3.3? `pcscd --version` Did you tweaked any flatpak permissions? `flatpak info -M com.yubico.yubioath`

```
[dad@DadsGram ~]$ flatpak info -M com.yubico.yubioath
[Context]
shared=ipc;
sockets=x11;wayland;fallback-x11;pcsc;
devices=all;
persistent=.ykman;

[Session Bus Policy]
org.kde.StatusNotifierWatcher=talk
org.freedesktop.secrets=talk

[dad@DadsGram ~]$ pcscd --version
pcsc-lite version 2.3.3
Copyright (C) 1999-2002 by David Corcoran <corcoran@musclecard.com>.
Copyright (C) 2001-2024 by Ludovic Rousseau <ludovic.rousseau@free.fr>.
Copyright (C) 2003-2004 by Damien Sauveron <sauveron@labri.fr>.
Report bugs to <pcsclite-muscle@lists.infradead.org>.
Enabled features: USB serial filter_names libudev polkit systemd Linux x86_64 ipcdir=/run/pcscd usbdropdir=/usr/lib/pcsc/drivers serialconfdir=/etc/reader.conf.d
MAX_READERNAME: 128, PCSCLITE_MAX_READERS_CONTEXTS: 16
```
Do the above permissions look OK to you?

**Comment by Erick555** [comment]
Yes, everything looks good and is identical to my setup. You may need to debug your pcsc daemon to get more info. Maybe ask upstream: https://github.com/LudovicRousseau/PCSC/issues

**Comment by Erick555** [comment]
One more thing, could you show `systemctl status pcscd.socket`? It should be `enabled` and `active`. If it's not then do `systemctl enable --now pcscd.socket` then close and start yubioath

Check if you have `/run/pcscd/pcscd.comm` file on system

**Comment by Aqua1ung** [comment]
> One more thing, could you show `systemctl status pcscd.socket`?

```
[dad@DadsGram ~]$ systemctl status pcscd.socket
● pcscd.socket - PC/SC Smart Card Daemon Activation Socket
     Loaded: loaded (/usr/lib/systemd/system/pcscd.socket; enabled; preset: disabled)
     Active: active (listening) since Sat 2025-10-18 14:47:55 EDT; 2h 21min ago
 Invocation: 15edca41e5f040e599d5c15f41fc0e9e
   Triggers: ● pcscd.service
     Listen: /run/pcscd/pcscd.comm (Stream)

Oct 18 14:47:55 DadsGram systemd[1]: Listening on PC/SC Smart Card Daemon Activation Socket.
```
 
> Check if you have `/run/pcscd/pcscd.comm` file on system

Yep, it's there alright. Seems to be empty though (0 bytes).

**Comment by Erick555** [comment]
It's empty because it's a socket file. In theory everything look right and should work.

**Comment by MBILC** [comment]
Hello,

Today I just installed CachyOS, and am having this same problem.

This is a brand new clean install, only other apps installed prior to Yubico Authenticator were KeepassXC, Signal.

As I was on mint linux 22 before, I just download the compressed tar.gzversions from the site, not flatpak installs or pacman install:

https://developers.yubico.com/yubioath-flutter/Releases/yubico-authenticator-latest-linux.tar.gz

yubico-authenticator-7.2.3-linux --> This was the version that ran fine under Mint Linux 6.14 Kernel.
yubico-authenticator-7.3.0-linux --> What I just tried on CachyOS, and it fails with the same above error.

Trying 7.2.3, also results in the same error.

Everything is installed, running and checks out fine, so there must be something with Yubico release?

Note, Passkeys work fine to pass through, only "Accounts" gives the error to check the pcscd service is running:


> **systemctl status pcscd** 
> ● pcscd.service - PC/SC Smart Card Daemon
>      Loaded: loaded (/usr/lib/systemd/system/pcscd.service; indirect; preset: disabled)
>      Active: active (running) since Fri 2026-01-09 18:11:08 MST; 25min ago
>  Invocation: dcf2a712dfe940cc9620b861b9031e2b
> TriggeredBy: ● pcscd.socket
>        Docs: man:pcscd(8)
>    Main PID: 7382 (pcscd)
>       Tasks: 6 (limit: 115661)
>      Memory: 1.2M (peak: 3.7M)
>         CPU: 38ms
>      CGroup: /system.slice/pcscd.service
>              └─7382 /usr/bin/pcscd --foreground --auto-exit
> 

> ❯ **pcscd --version**
> pcsc-lite version 2.4.1
> Copyright (C) 1999-2002 by David Corcoran <corcoran@musclecard.com>.
> Copyright (C) 2001-2024 by Ludovic Rousseau <ludovic.rousseau@free.fr>.
> Copyright (C) 2003-2004 by Damien Sauveron <sauveron@labri.fr>.
> Report bugs to <pcsclite-muscle@lists.infradead.org>.
> Enabled features: USB serial filter_names libudev polkit systemd Linux x86_64 ipcdir=/run/pcscd usbdropdir=/usr/lib/pcsc/drivers serialconfdir=/etc/reader.conf.d
> MAX_READERNAME: 128, PCSCLITE_MAX_READERS_CONTEXTS: 16


> ❯ **systemctl status pcscd.socket**
> ● pcscd.socket - PC/SC Smart Card Daemon Activation Socket
>      Loaded: loaded (/usr/lib/systemd/system/pcscd.socket; enabled; preset: disabled)
>      Active: active (running) since Fri 2026-01-09 17:57:45 MST; 40min ago
>  Invocation: d566d18371134edda4ca5d1f482ebedd
>    Triggers: ● pcscd.service
>      Listen: /run/pcscd/pcscd.comm (Stream)
>       Tasks: 0 (limit: 115661)
>      Memory: 0B (peak: 532K)
>         CPU: 851us
>      CGroup: /system.slice/pcscd.socket
> 
> Notice: journal has been rotated since unit was started, output may be incomplete.

From this:

> Check if you have /run/pcscd/pcscd.comm file on system

Exists.

**Comment by MBILC** [comment]
Addition, as i run the authenticator from CLI, this is what my terminal shows. I am using Plasma as my UI, not sure if that matter....

Yubikey is connected already.

> ~/Downloads/yubico-authenticator-7.3.0-linux
> ❯ ./authenticator
> Gdk-Message: 19:30:45.106: Unable to load  from the cursor theme
> 19:30:45.119 [desktop.init] INFO: Logging initialized, outputting to stderr
> 19:30:45.125 [desktop.init] INFO: Window hidden on startup: false
> 19:30:45.125 [desktop.init] INFO: Starting Helper subprocess: /home/********/Downloads/yubico-authenticator-7.3.0-linux/helper/authenticator-helper
> 19:30:45.128 [desktop.init] INFO: Helper process started
> 19:30:45.128 [main] INFO: Running Yubico Authenticator...
> {app_version: 7.3.0, dart: 3.9.2 (stable) (Wed Aug 27 03:49:40 2025 -0700) on "linux_x64", os: linux, os_version: Linux 6.18.3-2-cachyos #1 SMP PREEMPT_DYNAMIC Sat, 03 Jan 2026 23:14:07 +0000}
> 19:30:45.329 [helper.ykman.logging] INFO: Logging at level: INFO
> 19:30:45.329 [helper.helper.device] INFO: Log level set to: INFO
> 19:30:45.329 [desktop.init] INFO: Helper log level set
> 19:30:45.731 [desktop.devices] INFO: USB state change
> {"data":{"state":3167115292481917395,"pids":{"1031":1}},"actions":["get","scan"],"children":{"17499838":{"pid":1031,"name":"YubiKey 5 NFC FIPS","serial":**********}}}
> 19:30:45.732 [helper.helper.device] WARNING: Unable to connect via <class 'yubikit.core.smartcard.SmartCardConnection'>
> Traceback (most recent call last):
>   File "helper/device.py", line 368, in _refresh_data
>   File "ykman/device.py", line 254, in open_connection
> ValueError: Unsupported Connection type
> 19:30:45.732 [helper.helper.device] WARNING: Unable to connect via <class 'yubikit.core.otp.OtpConnection'>
> Traceback (most recent call last):
>   File "helper/device.py", line 368, in _refresh_data
>   File "ykman/device.py", line 254, in open_connection
> ValueError: Unsupported Connection type
> 19:30:45.792 [desktop.devices] INFO: USB state updated, unaccounted for: {}
> 19:30:45.813 [helper.helper.device] WARNING: Error opening connection
> Traceback (most recent call last):
>   File "helper/device.py", line 382, in ccid
>   File "helper/device.py", line 349, in _create_connection
>   File "ykman/device.py", line 254, in open_connection
> ValueError: Unsupported Connection type
> 19:30:45.813 [helper] INFO: Attempting recovery on "state-reset"
> 19:30:46.089 [helper.helper.device] WARNING: Unable to connect via <class 'yubikit.core.smartcard.SmartCardConnection'>
> Traceback (most recent call last):
>   File "helper/device.py", line 368, in _refresh_data
>   File "ykman/device.py", line 254, in open_connection
> ValueError: Unsupported Connection type
> 19:30:46.089 [helper.helper.device] WARNING: Unable to connect via <class 'yubikit.core.otp.OtpConnection'>
> Traceback (most recent call last):
>   File "helper/device.py", line 368, in _refresh_data
>   File "ykman/device.py", line 254, in open_connection
> ValueError: Unsupported Connection type
> 19:30:46.147 [helper.helper.device] WARNING: Error opening connection
> Traceback (most recent call last):
>   File "helper/device.py", line 382, in ccid
>   File "helper/device.py", line 349, in _create_connection
>   File "ykman/device.py", line 254, in open_connection
> ValueError: Unsupported Connection type
> 19:30:46.425 [helper.helper.device] WARNING: Unable to connect via <class 'yubikit.core.smartcard.SmartCardConnection'>
> Traceback (most recent call last):
>   File "helper/device.py", line 368, in _refresh_data
>   File "ykman/device.py", line 254, in open_connection
> ValueError: Unsupported Connection type
> 19:30:46.425 [helper.helper.device] WARNING: Unable to connect via <class 'yubikit.core.otp.OtpConnection'>
> Traceback (most recent call last):
>   File "helper/device.py", line 368, in _refresh_data
>   File "ykman/device.py", line 254, in open_connection
> ValueError: Unsupported Connection type
> 19:30:46.483 [helper.helper.device] WARNING: Error opening connection
> Traceback (most recent call last):
>   File "helper/device.py", line 382, in ccid
>   File "helper/device.py", line 349, in _create_connection
>   File "ykman/device.py", line 254, in open_connection
> ValueError: Unsupported Connection type
> 19:30:46.483 [helper] INFO: Attempting recovery on "state-reset"
> 19:30:46.869 [helper.helper.device] WARNING: Unable to connect via <class 'yubikit.core.smartcard.SmartCardConnection'>
> Traceback (most recent call last):
>   File "helper/device.py", line 368, in _refresh_data
>   File "ykman/device.py", line 254, in open_connection
> ValueError: Unsupported Connection type
> 19:30:46.869 [helper.helper.device] WARNING: Unable to connect via <class 'yubikit.core.otp.OtpConnection'>
> Traceback (most recent call last):
>   File "helper/device.py", line 368, in _refresh_data
>   File "ykman/device.py", line 254, in open_connection
> ValueError: Unsupported Connection type
> 19:30:46.927 [helper.helper.device] WARNING: Error opening connection
> Traceback (most recent call last):
>   File "helper/device.py", line 382, in ccid
>   File "helper/device.py", line 349, in _create_connection
>   File "ykman/device.py", line 254, in open_connection
> ValueError: Unsupported Connection type
> 19:30:46.928 [helper.helper.device] WARNING: Error opening connection
> Traceback (most recent call last):
>   File "helper/device.py", line 382, in ccid
>   File "helper/device.py", line 349, in _create_connection
>   File "ykman/device.py", line 254, in open_connection
> ValueError: Unsupported Connection type

**Comment by MBILC** [comment]
I added the udev rules in, which i did not have and rebooted, same error still:
https://github.com/Yubico/libfido2/blob/main/udev/70-u2f.rules

**Comment by MBILC** [comment]
**Solution found:**

From a 2022 Suse thread: (I am running CachyOS but would apply for other Arc distro's)
https://github.com/Yubico/yubioath-flutter/issues/876#issuecomment-1352238960

`sudo pacman -S ccid`

Then restart:
```
systemctl restart pcscd.socket
sudo systemctl restart pcscd.service
```

**Comment by Aqua1ung** [comment]
> **Solution found:**
> 
> From a 2022 Suse thread: (I am running CachyOS but would apply for other Arc distro's) [Yubico/yubioath-flutter#876 (comment)](https://github.com/Yubico/yubioath-flutter/issues/876#issuecomment-1352238960)
> 
> `sudo pacman -S ccid`

Thanks. Now I am getting a _different_ type of error: `Failed connecting over ccid and otp`. What further dependency might I be missing this time around?

Edit: Here's the log displayed during a command line run:
```
[dad@DadsGram ~]$ flatpak run --branch=stable --arch=x86_64 --command=authenticator com.yubico.yubioath
Gdk-Message: 12:32:20.753: Unable to load  from the cursor theme
12:32:20.774 [desktop.init] INFO: Logging initialized, outputting to stderr
12:32:20.776 [desktop.init] INFO: Window hidden on startup: false
12:32:20.776 [desktop.init] INFO: Starting Helper subprocess: /app/bin/helper/authenticator-helper
12:32:20.779 [desktop.init] INFO: Helper process started
12:32:20.780 [main] INFO: Running Yubico Authenticator...
{app_version: 7.3.0, dart: 3.9.2 (stable) (Wed Aug 27 03:49:40 2025 -0700) on "linux_x64", os: linux, os_version: Linux 6.18.4-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Fri, 09 Jan 2026 19:43:35 +0000}
12:32:21.012 [helper.ykman.logging] INFO: Logging at level: INFO
12:32:21.012 [helper.helper.device] INFO: Log level set to: INFO
12:32:21.012 [desktop.init] INFO: Helper log level set
12:32:21.383 [desktop.devices] INFO: USB state change
{"data":{"state":3826618381412362355,"pids":{"1031":1}},"actions":["get","scan"],"children":{"xxxxxxxx":{"pid":1031,"name":"YubiKey 5C Nano","serial":xxxxxxxx}}}
12:32:21.415 [desktop.devices] INFO: USB state updated, unaccounted for: {}
12:32:21.473 [helper.helper.device] WARNING: Error opening connection
Traceback (most recent call last):
  File "helper/device.py", line 393, in otp
  File "helper/device.py", line 349, in _create_connection
  File "ykman/device.py", line 254, in open_connection
ValueError: Unsupported Connection type
12:32:21.473 [helper] INFO: Attempting recovery on "state-reset"
12:32:21.738 [helper.helper.device] WARNING: Error opening connection
Traceback (most recent call last):
  File "helper/device.py", line 393, in otp
  File "helper/device.py", line 349, in _create_connection
  File "ykman/device.py", line 254, in open_connection
ValueError: Unsupported Connection type
12:32:21.738 [desktop.otp.state] WARNING: Failed connecting to yubiotp via UsbInterface.otp
12:32:22.044 [desktop.otp.state] WARNING: Failed connecting to yubiotp via UsbInterface.ccid
12:32:22.155 [helper.helper.device] WARNING: Error opening connection
Traceback (most recent call last):
  File "helper/device.py", line 393, in otp
  File "helper/device.py", line 349, in _create_connection
  File "ykman/device.py", line 254, in open_connection
ValueError: Unsupported Connection type
12:32:22.156 [helper] INFO: Attempting recovery on "state-reset"
12:32:22.438 [helper.helper.device] WARNING: Error opening connection
Traceback (most recent call last):
  File "helper/device.py", line 393, in otp
  File "helper/device.py", line 349, in _create_connection
  File "ykman/device.py", line 254, in open_connection
ValueError: Unsupported Connection type
12:32:22.438 [desktop.otp.state] WARNING: Failed connecting to yubiotp via UsbInterface.otp
12:32:22.466 [desktop.otp.state] WARNING: Failed connecting to yubiotp via UsbInterface.ccid
12:32:22.468 [helper.helper.device] WARNING: Error opening connection
Traceback (most recent call last):
  File "helper/device.py", line 393, in otp
  File "helper/device.py", line 349, in _create_connection
  File "ykman/device.py", line 254, in open_connection
ValueError: Unsupported Connection type
12:32:22.468 [desktop.otp.state] WARNING: Failed connecting to yubiotp via UsbInterface.otp
12:32:22.492 [desktop.otp.state] WARNING: Failed connecting to yubiotp via UsbInterface.ccid
12:33:12.558 [helper.helper.device] WARNING: Error opening connection
Traceback (most recent call last):
  File "helper/device.py", line 393, in otp
  File "helper/device.py", line 349, in _create_connection
  File "ykman/device.py", line 254, in open_connection
ValueError: Unsupported Connection type
12:33:12.558 [desktop.otp.state] WARNING: Failed connecting to yubiotp via UsbInterface.otp
12:33:12.586 [desktop.otp.state] WARNING: Failed connecting to yubiotp via UsbInterface.ccid
12:33:54.608 [helper.helper.device] WARNING: Error opening connection
Traceback (most recent call last):
  File "helper/device.py", line 393, in otp
  File "helper/device.py", line 349, in _create_connection
  File "ykman/device.py", line 254, in open_connection
ValueError: Unsupported Connection type
12:33:54.608 [desktop.otp.state] WARNING: Failed connecting to yubiotp via UsbInterface.otp
12:33:54.636 [desktop.otp.state] WARNING: Failed connecting to yubiotp via UsbInterface.ccid
```

**Comment by Erick555** [comment]
You may check with `ykman info` if your yubikey supports relevant connection modes. In general non-flatpak issues can be reported in [upstream](https://github.com/Yubico/yubioath-flutter/issues) or in distro channels.

**Comment by Aqua1ung** [comment]
Forgot to mention that this error happens only when clicking on the "Slots" tab. All the other sections work fine.

![Image](https://github.com/user-attachments/assets/55218a0f-0cff-4d12-81b5-df068c442358)

**Comment by nasiralamreeki** [comment]
> Forgot to mention that this error happens only when clicking on the "Slots" tab. All the other sections work fine.
> 
> ![Image](https://github.com/user-attachments/assets/55218a0f-0cff-4d12-81b5-df068c442358)

It's been over a year unlikely any fix is coming

**Comment by persicsb** [comment]
I can confirm that this bug exists on Fedora 43: failed connecting over ccid and otp

**Comment by Erick555** [comment]
You may check `systemctl status pcscd.service`. Some system updates may require restarting pcscd daemon, re-plugging yubikey or reboting system.

**Comment by edgan** [comment]
> I can confirm that this bug exists on Fedora 43: failed connecting over ccid and otp

I have been using my `YubiKey 5C NFC` with `Fedora 43` without issue.

```
cat /etc/redhat-release 
Fedora release 43 (Forty Three)

flatpak list | grep -i yub
Yubico Authenticator	com.yubico.yubioath	7.3.2	stable	system

rpm -qa | grep pcsc
pcsc-lite-libs-2.3.3-2.fc43.x86_64
pcsc-lite-2.3.3-2.fc43.x86_64
pcsc-lite-devel-2.3.3-2.fc43.x86_64
pcsc-lite-ccid-1.7.0-2.fc43.x86_64
```

**Comment by persicsb** [comment]
The services are up and running, yet, Yubico Authenticator cannot connect to pcscd.

```
00:17:14.014 [helper.helper.device] WARNING: Error opening connection
Traceback (most recent call last):
  File "helper/device.py", line 393, in otp
  File "helper/device.py", line 349, in _create_connection
  File "ykman/device.py", line 254, in open_connection
ValueError: Unsupported Connection type
00:17:14.014 [desktop.otp.state] WARNING: Failed connecting to yubiotp via UsbInterface.otp
00:17:14.063 [helper.ykman.pcsc] INFO: Failed to get exclusive CCID access
00:17:14.079 [desktop.otp.state] WARNING: Failed connecting to yubiotp via UsbInterface.ccid
00:17:15.687 [helper.helper.device] WARNING: Error opening connection
Traceback (most recent call last):
  File "helper/device.py", line 393, in otp
  File "helper/device.py", line 349, in _create_connection
  File "ykman/device.py", line 254, in open_connection
ValueError: Unsupported Connection type
00:17:15.687 [desktop.otp.state] WARNING: Failed connecting to yubiotp via UsbInterface.otp
00:17:15.737 [helper.ykman.pcsc] INFO: Failed to get exclusive CCID access
00:17:15.752 [desktop.otp.state] WARNING: Failed connecting to yubiotp via UsbInterface.ccid
```

**Comment by Erick555** [comment]
Something on your system is blocking access, try re-plugging yubikey or report it [upstream](https://github.com/Yubico/yubioath-flutter)
